# Generated by Django 3.2.14 on 2022-08-17 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_timestamp'),
        ('comanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='socio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socios.socio'),
            preserve_default=False,
        ),
    ]
