# Generated by Django 3.2.14 on 2023-01-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepagos', '0004_pago_usuario'),
        ('comanda', '0002_comanda_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='prepago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prepagos.prepago'),
        ),
    ]
