# Generated by Django 3.2.14 on 2023-01-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepagos', '0004_pago_usuario'),
        ('comanda', '0004_auto_20230102_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='prepago',
            field=models.ManyToManyField(blank=True, to='prepagos.Prepago'),
        ),
    ]
