# Generated by Django 3.2.14 on 2022-08-17 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='operador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operadores.operador'),
            preserve_default=False,
        ),
    ]
