# Generated by Django 3.2.14 on 2022-08-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_auto_20220802_2258'),
        ('pedidos', '0002_pedido_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='detalles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.detalles'),
            preserve_default=False,
        ),
    ]
