# Generated by Django 3.2.14 on 2022-09-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedidoitem_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_final',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
