# Generated by Django 3.2.14 on 2022-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='precio_publico',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
