# Generated by Django 3.2.14 on 2022-08-16 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.licencia', verbose_name='Operador Club')),
            ],
        ),
    ]
