# Generated by Django 2.2.13 on 2021-01-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('inserted_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monto',
                'verbose_name_plural': 'Montos',
            },
        ),
    ]
