# Generated by Django 3.2.14 on 2022-09-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='status',
            field=models.CharField(choices=[('my', 'Mayorista'), ('pc', 'Productor Calificado'), ('ce', 'Constructor del Exito'), ('cm', 'Consultor Mayor'), ('ds', 'Distribuidor'), ('au', 'Oro'), ('ag', 'Plata'), ('ae', 'Bronce'), ('cl', 'Cliente')], default='my', max_length=2),
        ),
    ]
