# Generated by Django 3.2.14 on 2022-09-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_licencia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
