# Generated by Django 3.2.14 on 2022-08-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_timestamp'),
        ('bot', '0006_auto_20220409_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.socio'),
        ),
    ]
