# Generated by Django 2.2.13 on 2021-03-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_porcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='palabras_clave',
            field=models.TextField(blank=True, null=True),
        ),
    ]
