# Generated by Django 2.2.22 on 2021-06-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_categoria_palabras_clave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
    ]
