# Generated by Django 2.2.22 on 2021-06-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20210615_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('nutricion', (('interna', 'INTERNA'), ('externa', 'EXTERNA'))), ('promocion', (('utensilios', 'UTENSILIOS'), ('literatura', 'LITERATURA')))], default='interna', max_length=32),
        ),
    ]
