# Generated by Django 2.2.22 on 2022-01-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_categoria_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porcion',
            old_name='cantidad',
            new_name='medidas_porcion',
        ),
        migrations.RenameField(
            model_name='porcion',
            old_name='precio',
            new_name='precio_medida',
        ),
        migrations.AddField(
            model_name='porcion',
            name='porciones_frasco',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='porcion',
            name='tipo_medida',
            field=models.CharField(blank=True, choices=[('mililitros', 'ML'), ('gramos', 'GR')], max_length=64, null=True),
        ),
    ]
