# Generated by Django 2.2.22 on 2022-02-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_auto_20220208_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
