# Generated by Django 2.2.22 on 2022-03-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_categoria_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='detalle',
            field=models.TextField(blank=True, default='\n        {}\n        Cantidad: {}\n        PV: {}\n        Distribuidor - 25% : {:>10} Bs.\n        Consultor - 35% : {:>14} Bs.\n        Constructor - 42% : {:>10} Bs.\n        Mayorista - 50% : {:>14} Bs.\n        #\n        Cliente : {} Bs.\n    ', null=True),
        ),
    ]
