# Generated by Django 2.2.22 on 2022-03-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_auto_20220314_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sabor',
            old_name='sabor',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='detalle',
            field=models.TextField(blank=True, default='{}\nCantidad: {}\nPV: {}\nDistribuidor - 25% : {:>10} Bs.\nConsultor - 35% : {:>14} Bs.\nConstructor - 42% : {:>10} Bs.\nMayorista - 50% : {:>14} Bs.\n#\nCliente : {} Bs.\n    ', null=True),
        ),
    ]
