# Generated by Django 3.2.13 on 2022-06-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_auto_20220409_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porcion',
            name='categoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria'),
        ),
    ]
