# Generated by Django 3.2.13 on 2022-07-03 03:27

from django.db import migrations, models
import recetas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_alter_porcion_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porcion',
            name='medida',
        ),
        migrations.AddField(
            model_name='porcion',
            name='cantidad',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='porcion',
            name='cantidad_decimal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='porcion',
            name='unidad',
            field=models.CharField(default='gr', max_length=50, validators=[recetas.validators.validar_unidad_de_medida]),
            preserve_default=False,
        ),
    ]
