# Generated by Django 3.2.14 on 2022-07-26 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_auto_20220702_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='cliente_bs',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='cliente_sus',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='consultor_mayor',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='distribuidor',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='mayorista',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='productor_calificado',
        ),
        migrations.CreateModel(
            name='PrecioDistribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribuidor', models.FloatField(max_length=10)),
                ('consultor_mayor', models.FloatField(max_length=10)),
                ('productor_calificado', models.FloatField(max_length=10)),
                ('mayorista', models.FloatField(max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioClientePreferente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oro', models.FloatField(max_length=10)),
                ('plata', models.FloatField(max_length=10)),
                ('bronce', models.FloatField(max_length=10)),
                ('cliente', models.FloatField(max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
        ),
    ]
