# Generated by Django 3.2.14 on 2022-07-26 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_auto_20220726_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioclientepreferente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='precioclientepreferente',
            name='edited_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='precioclientepreferente',
            name='inserted_on',
            field=models.DateField(auto_now_add=True, default=datetime.date(2022, 7, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preciodistribuidor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preciodistribuidor',
            name='edited_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='preciodistribuidor',
            name='inserted_on',
            field=models.DateField(auto_now_add=True, default=datetime.date(2022, 7, 26)),
            preserve_default=False,
        ),
    ]
