# Generated by Django 3.2.14 on 2022-08-03 02:31

from django.db import migrations, models
import recetas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_auto_20220726_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalles',
            options={'managed': True, 'verbose_name': 'Detalle', 'verbose_name_plural': 'Detalles'},
        ),
        migrations.RenameField(
            model_name='detalles',
            old_name='detalles',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='detalles',
            name='cantidad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalles',
            name='cantidad_decimal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalles',
            name='sabor',
            field=models.CharField(default='chocolate', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalles',
            name='unidad',
            field=models.CharField(default='gr', max_length=50, validators=[recetas.validators.validar_unidad_de_medida]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='detalle',
            field=models.TextField(blank=True, default='{}\nCantidad: {}\nPV: {}\nDistribuidor - 25% : {:>10} Bs.\nConsultor - 35% : {:>14} Bs.\nConstructor - 42% : {:>10} Bs.\nMayorista - 50% : {:>14} Bs.', null=True),
        ),
    ]
