# Generated by Django 3.2.14 on 2022-08-03 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0023_auto_20220802_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='pais',
        ),
        migrations.AddField(
            model_name='detalles',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.pais'),
        ),
    ]
