# Generated by Django 3.2.14 on 2022-09-08 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_auto_20220802_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria'),
        ),
    ]
