# Generated by Django 3.2.14 on 2023-01-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0025_alter_detalles_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabrasClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=32)),
                ('categoria', models.ManyToManyField(blank=True, to='productos.Categoria')),
            ],
        ),
    ]
