# Generated by Django 3.2.14 on 2023-01-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_palabrasclave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sabor',
            name='categoria',
        ),
        migrations.AddField(
            model_name='sabor',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='productos.Categoria'),
        ),
    ]
