# Generated by Django 3.2.14 on 2022-10-04 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0002_socio_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=10)),
                ('descuento', models.IntegerField(default=10)),
                ('valor', models.FloatField()),
                ('pagado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
            ],
        ),
    ]
