# Generated by Django 3.2.14 on 2022-10-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepago',
            name='descuento_decimal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
