# Generated by Django 3.2.14 on 2022-10-09 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prepagos', '0002_prepago_descuento_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prepago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prepagos.prepago')),
            ],
        ),
    ]
